python analyzeTemperatures.py 002 -b
python analyzeTemperatures.py 003 -b
python analyzeTemperatures.py 004 -b
python analyzeTemperatures.py 005 -b
python analyzeTemperatures.py 006 -b
python analyzeTemperatures.py 007 -b
python analyzeTemperatures.py 008 -b
python analyzeTemperatures.py 009 -b
python analyzeTemperatures.py 010 -b
python analyzeTemperatures.py 011 -b
python analyzeTemperatures.py 012 -b
python analyzeTemperatures.py 013 -b
python analyzeTemperatures.py 014 -b
python analyzeTemperatures.py 015 -b
python analyzeTemperatures.py 016 -b
python analyzeTemperatures.py 017 -b
python analyzeTemperatures.py 018 -b
python analyzeTemperatures.py 019 -b
python analyzeTemperatures.py 020 -b
python analyzeTemperatures.py 021 -b
python analyzeTemperatures.py 022 -b
python analyzeTemperatures.py 023 -b
python analyzeTemperatures.py 024 -b
python analyzeTemperatures.py 025 -b
python analyzeTemperatures.py 026 -b
python analyzeTemperatures.py 027 -b
python analyzeTemperatures.py 028 -b
python analyzeTemperatures.py 029 -b


